containerized: "/projects/humgen/pipelines/dna-seq-nanopore/container.sif"

import pandas as pd
import os
import yaml

with open("config/config.yaml", "r") as file:
    config = yaml.safe_load(file)

BASEDIR = os.path.dirname(workflow.snakefile)
REFERENCE = f"results/resources/{config["reference"]}.fasta"

include: "rules/common.smk"
include: "rules/basecalling.smk"
include: "rules/mapping.smk"
include: "rules/reference.smk"
include: "rules/snp_calling.smk"
include: "rules/sv_calling.smk"
include: "rules/str_calling.smk"
include: "rules/filtering.smk"
#include: "rules/methyl.smk"
include: "rules/jasmine.smk"
include: "rules/annotate.smk"
include: "rules/visualization.smk"
include: "rules/qc.smk"
include: "rules/cadd.smk"

ruleorder: annotate_snps_gnomad > index_bcf
ruleorder: peddy_vcf > tabix

wildcard_constraints:
    group="|".join(groups),
    sample="|".join(sample_names),

# all_input = [f"results/basecalls/{row['sample_name']}.{row['unit_name']}.ubam" for _, row in units.iterrows()]


rule all:
    input:
        # expand("results/str/{sample}.bed", sample=units["sample_name"]),
        # expand("results/snps/{sample}.annotated.vcf.gz", sample=units["sample_name"]),
        # expand("results/sv_snf/{sample}.snf", sample=units["sample_name"]),
        # expand("results/sv/{group}.vcf", group=groups),
        #expand("results/alignment/{sample}.cram", sample=units["sample_name"]),
        # expand("results/tables/{group}.sv.tsv", group=groups),
        # expand("results/sv/{group}.annotated.repeats.bcf", group=groups),
        # expand("results/sv/{group}.annotated.repeats.bcf", group=groups)
        expand("results/tables/{group}.snps.maf.0.01.tsv", group=groups),
        # expand("results/tables/{group}.snps.tsv", group=groups),
        # expand("results/tables/{sample}.str.tsv", sample=units["sample_name"]),
        # expand("results/str/{sample}.annotated.vep.bcf", sample=units["sample_name"]),
        #expand("results/snps/{sample}.vcf.gz", sample=units["sample_name"]),
        #expand("results/methylation/{sample}_1.bed", sample=units["sample_name"]),
        #expand("results/methylation/bismark/{sample}.bismark.cov.gz", sample=units["sample_name"]),


# print(len(list(controls["base_name"])))


basecall_units = []
for sample in sample_names:
    basecall_units.extend(expand(f"results/basecalls/{sample}.{{unit}}.ubam", unit=get_units_for_sample(sample)))


rule only_inhouse:
    input:
        expand("results/snps/{group}.annotated.inhouse.bcf", group=groups)

rule only_qc:
    input:
        "results/qc/multiqc.html"

rule only_nanoplot:
    input:
        expand("results/qc/nanoplot/{sample}/{sample}.NanoStats.txt", sample=sample_names)

rule only_peddy:
    input:
        expand("results/qc/peddy/{group}.html", group=groups)

rule only_jasmine_fix:
    input:
        expand("results/sv/{group}.jasmine_fix.vcf", group=groups)

rule only_jasmine:
    input:
        expand("results/sv/{group}.control_annotated.vcf", group=groups)

rule only_download_controls:
    input:
        expand("results/controls/{vcf}.vcf.gz", vcf=controls)

rule only_mapping:
    input:
        expand("results/alignment/{sample}.cram", sample=units["sample_name"]),

rule only_mapping_avail:
    input:
        lambda _: expand("results/alignment/{sample}.cram", sample=glob_wildcards("results/basecalls_sample/{sample}.ubam").sample),

rule only_basecalling_units:
    input:
        basecall_units

rule only_basecalling:
    input:
        expand("results/basecalls_sample/{sample}.ubam", sample=units["sample_name"])

rule only_clair:
    input:
        expand("results/clair3_new/{sample}/phased_merge_output.vcf.gz", sample=units["sample_name"])
        
rule only_snp_calling:
    input:
        expand("results/snps/samples/{group}.bcf", group=groups)

rule only_snp_gnomad:
    input:
        expand("results/snps/{group}.annotated.gnomad.bcf", group=groups)

rule only_snp_vep:
    input:
        expand("results/snps/{group}.annotated.vep.vcf.gz", group=groups)

rule only_snf:
    input:
        expand("results/sv_snf/{sample}.snf", sample=sample_names)

rule only_sv_annotated:
    input:
        expand("results/sv/{group}.annotated.repeats.bcf", group=groups)

rule only_sv_table:
    input:
        expand("results/tables/{group}.sv.tsv", group=groups)

rule only_sv_calling:
    input:
        expand("results/sv/{group}.vcf", group=groups)


rule test:
    input:
        lambda _: expand("results/alignment/{sample}.cram", sample=["818-33", "818-52"]),
